name: Build Windows app
on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm version 1.0.${{ github.run_number }} --no-git-tag-version
      - run: npm run dist
      - uses: actions/upload-artifact@v4
        with:
          name: Motion-Pack-for-Windows
          path: dist/*.exe
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Motion Pack 1.0.${{ github.run_number }}
          make_latest: true
          files: |
            dist/*.exe
            dist/*.blockmap
            dist/latest.yml
